---
# tasks file for preconf_centos
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
  when: upgrade_all | bool
  tags:
    - skip_ansible_lint

- name: EPEL install CentOS 7 / RHEL 7
  yum:
    name: epel-release
    state: present
  when: install_epel | bool and (ansible_distribution == "CentOS" or ansible_distribution == "RedHat") and ansible_distribution_major_version == "7"

- name: Install start soft
  yum:
    name: "{{ preconf_packages | list }}"
    state: installed
  when: start_soft | bool and install_epel | bool

- name: Install firewalld
  yum:
    name: firewalld
    state: present
  when: init_firewalld | bool

- name: Start and Enable firewalld
  systemd:
    name: firewalld
    enabled: true
    state: started
  when: init_firewalld | bool

- name: Change hostname system-wide
  hostname:
    name: '{{ hostname }}'
  # Hostname is not changing in docker
  when: change_hostname | bool and ansible_virtualization_type != "docker"

- name: Change hostname in sysctl
  sysctl:
    name: kernel.hostname
    value: '{{ hostname }}'
    sysctl_file: /etc/sysctl.conf
    reload: true
  when: change_hostname | bool

- name: Disable IPv6 in sysctl
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_file: /etc/sysctl.conf
    reload: true
  with_items:
    - { name: 'net.ipv6.conf.all.disable_ipv6', value: '1' }
    - { name: 'net.ipv6.conf.all.autoconf', value: '0' }
  when: disable_ipv6 | bool
